// <auto-generated />
using System;
using IWI_Backend.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IWI_Backend.Api.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20260913145109_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("backrooms")
                .HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("IWI_Backend.Api.Entities.HeroSlideEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ButtonLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.ToTable("HeroSlides", "backrooms");
                });

            modelBuilder.Entity("IWI_Backend.Api.Entities.HeroSlideEntity", b =>
                {
                    b.OwnsOne("IWI_Backend.Api.Entities.MediaRef", "Image", b1 =>
                        {
                            b1.Property<Guid>("HeroSlideEntityId");

                            b1.Property<string>("ContentType")
                                .IsRequired();

                            b1.Property<string>("Id");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<long>("Size");

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("HeroSlideEntityId");

                            b1.ToTable("HeroSlides", "backrooms");

                            b1
                                .ToJson("Image")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("HeroSlideEntityId");
                        });

                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
