export * from './bulletin-board.service';
import { BulletinBoardService } from './bulletin-board.service';
export * from './bulletin-board.serviceInterface';
export * from './iwi-backend-api.service';
import { IWIBackendApiService } from './iwi-backend-api.service';
export * from './iwi-backend-api.serviceInterface';
export * from './infotainment.service';
import { InfotainmentService } from './infotainment.service';
export * from './infotainment.serviceInterface';
export * from './instagram.service';
import { InstagramService } from './instagram.service';
export * from './instagram.serviceInterface';
export * from './o-phase.service';
import { OPhaseService } from './o-phase.service';
export * from './o-phase.serviceInterface';
export * from './protocol.service';
import { ProtocolService } from './protocol.service';
export * from './protocol.serviceInterface';
export const APIS = [BulletinBoardService, IWIBackendApiService, InfotainmentService, InstagramService, OPhaseService, ProtocolService];
