/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BulletinPostDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiBulletinPostsGetRequestParams {
    board?: string;
    limit?: number;
    offset?: number;
}

export interface ApiBulletinRefreshGetRequestParams {
    courseOfStudy?: string;
}


export interface BulletinBoardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBulletinPostsGet(requestParameters: ApiBulletinPostsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<BulletinPostDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBulletinRefreshGet(requestParameters: ApiBulletinRefreshGetRequestParams, extraHttpRequestParams?: any): Observable<boolean>;

}
