/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SlideDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiInfoNameGetRequestParams {
    name: string;
}


export interface InfotainmentServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiInfoGet(extraHttpRequestParams?: any): Observable<Array<SlideDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiInfoNameGet(requestParameters: ApiInfoNameGetRequestParams, extraHttpRequestParams?: any): Observable<SlideDto>;

    /**
     * 
     * 
*/
    apiInfoRefreshGet(extraHttpRequestParams?: any): Observable<{}>;

}
