/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { InstagramFeedDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiInstaInstaMediaNameGetRequestParams {
    name: string;
}

export interface ApiInstaInstaPostsGetRequestParams {
    limit?: number;
}


export interface InstagramServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiInstaInstaMediaNameGet(requestParameters: ApiInstaInstaMediaNameGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiInstaInstaPostsGet(requestParameters: ApiInstaInstaPostsGetRequestParams, extraHttpRequestParams?: any): Observable<InstagramFeedDto>;

    /**
     * 
     * 
*/
    apiInstaRefreshGet(extraHttpRequestParams?: any): Observable<{}>;

}
