/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { OPhaseInfoDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiOphaseTimetableGetRequestParams {
    course?: string;
}


export interface OPhaseServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiOphaseGet(extraHttpRequestParams?: any): Observable<OPhaseInfoDto>;

    /**
     * 
     * 
*/
    apiOphaseRefreshGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiOphaseTimetableGet(requestParameters: ApiOphaseTimetableGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
