/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';


export interface ApiProtocolsFileNameGetRequestParams {
    fileName: string;
}


export interface ProtocolServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiProtocolsFileNameGet(requestParameters: ApiProtocolsFileNameGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    apiProtocolsGet(extraHttpRequestParams?: any): Observable<{ [key: string]: Array<string> | undefined; }>;

    /**
     * 
     * 
*/
    apiProtocolsRefreshGet(extraHttpRequestParams?: any): Observable<{}>;

}
