services:
  web:
    build:
      context: ../ui
      dockerfile: Dockerfile
      secrets:
        - nextcloud_url
    image: iwi-website:latest
    container_name: iwi-website
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../api
      dockerfile: ./IWI-Backend.Api/Dockerfile
    image: iwi-backend:latest
    container_name: iwi-backend
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - Sync__CacheDirectory=/home/app/cache
    user: "1654:1654"
    volumes:
      - media_cache:/home/app/cache
    ports:
      - "127.0.0.1:5200:8080"

secrets:
  nextcloud_url:
    environment: NEXTCLOUD_URL

volumes:
  media_cache: