/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BulletinPostDto { 
    title?: string | null;
    type?: string | null;
    content?: string | null;
    id?: number;
    creator?: string | null;
    coursesOfStudy?: Array<string> | null;
    departments?: Array<string> | null;
    publicationTimestamp?: string;
}

