/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstagramChildDto } from './instagram-child-dto';


export interface InstagramPostDto { 
    id?: string | null;
    media_type?: string | null;
    media_url?: string | null;
    thumbnail_url?: string | null;
    caption?: string | null;
    permalink?: string | null;
    timestamp?: string | null;
    like_count?: number | null;
    comments_count?: number | null;
    children?: Array<InstagramChildDto> | null;
    width?: number | null;
    height?: number | null;
}

