/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InstagramUserDto { 
    id?: string | null;
    username?: string | null;
    profile_picture_url?: string | null;
}

