/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InstagramChildDto { 
    id?: string | null;
    media_type?: string | null;
    media_url?: string | null;
    width?: number | null;
    height?: number | null;
}

