/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstagramPostDto } from './instagram-post-dto';
import { InstagramUserDto } from './instagram-user-dto';


export interface InstagramFeedDto { 
    user?: InstagramUserDto;
    data?: Array<InstagramPostDto> | null;
}

