/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Vorkurse } from './vorkurse';
import { Zeitraum } from './zeitraum';


export interface OPhaseInfoDto { 
    semester?: string | null;
    vorkurse?: Vorkurse;
    orientierungsphase?: Zeitraum;
    vorlesungszeit?: Zeitraum;
    changedAt?: string | null;
    readonly semesterName?: string | null;
    readonly semesterYear?: string | null;
}

