/**
 * IWI-Backend.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SlideDto { 
    type?: string | null;
    src?: string | null;
    duration?: number;
    alt?: string | null;
}

