name: Deploy Website

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 1
          rm: true
          debug: true

      - name: Build and start container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: INSTAGRAM_TOKEN,NEXTCLOUD_URL
          script: |
            set -e
            cd ${{ secrets.DEPLOY_PATH }}/deploy
            export INSTAGRAM_TOKEN WEBDAV_USERNAME WEBDAV_PASSWORD NEXTCLOUD_URL
            docker compose down
            docker compose up -d --build
            docker image prune -f
        env:
          INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
          NEXTCLOUD_URL: ${{ secrets.NEXTCLOUD_URL }}
          WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
